<div id="main">
	<div id="filter-list">
		<div class="filter-title-div"><span class="filter-title">by category</span></div>
		<?php foreach ($this->categoryArray as $category): ?>

        <div class="filter-link-div">
        	<a href="<?php echo $this->url(
            array('controller'=>'index', 'action'=> $category),
            'default',
            true)?>" class="filter-link">
            <?php echo $category;?>
       	 	</a>
       	 </div>
       	 <div class="filter-link-div">
       	 	<span class="filter-separator">|</span>
       	 </div>

    	<?php endforeach; ?>
	</div>

	<div id="filter-list">
		<div class="filter-title-div"><span class="filter-title">by device</span></div>
		<?php foreach ($this->deviceArray as $device): ?>
 		<div class="filter-link-div">
 			<a href="<?php
	        echo $this->url(
	            array('controller'=>'index', 'action'=> 'all'),
	            'default',
	            true) . '/' . $device; ?>" class="filter-link">
		    <?php echo $device ?>
	    	</a>
	    </div>
	    <div class="filter-link-div">
	    	<span class="filter-separator">|</span></div>
	    <?php endforeach; ?>
		</div>
</div>