<div id="main">
	<div id="form-div">
		<form enctype="multipart/form-data" action="/index/add" method="POST">
			<div class="product-add-text">Product name:</div>
			<input class="product-add-input" name="product_name" type="text" /> <br />
			<div class="product-add-text">Product device:</div>
			<select class="product-add-input" name="product_device">
				<?php
  				foreach ($this->deviceArray as $device) {
					echo '<option value="';
					echo $device['device-id'] . '">' . $device['device-name'];
					echo '</option>';
				}
				?>
			</select><br />
			<div class="product-add-text">Product category:</div>
			<select class="product-add-input" name="product_category">
				<?php
  				foreach ($this->categoryArray as $category) {
					echo '<option class="category-option" value="';
					echo $category['category-id'] . '">' . $category['category-name'];
					echo '</option>';
				}
				?>
			</select><br />
			<div class="product-add-text">Product description:</div>
			<input class="product-add-input" name="product_description" type="text" /> <br />
			<div class="product-add-text">Product price:</div>
			<input class="product-add-input" name="product_price" type="text" /> <br />
			<div class="product-add-text">Product quantity:</div>
			<input class="product-add-input" name="product_quantity" type="text" /> <br />
			<div class="product-add-text">Upload image:</div>
			<input class="product-add-input" name="product_image" type="file" /> <br />
			<input class="product-add-submit" type="submit" value="Add product" />
		</form>
	</div>
</div>