<div id="main">
	<div id="form-div">
		<form enctype="multipart/form-data" action="/index/angular" method="POST">
			Product name:
			<input name="product_name" type="text" /> <br />
			Product category:
			<input name="product_category" type="text" /> <br />
			Product device:
			<input name="product_device" type="text" /> <br />
			Product description:
			<input name="product_description" type="text" /> <br />
			Product price:
			<input name="product_price" type="text" /> <br />
			Product quantity:
			<input name="product_quantity" type="text" /> <br />
			Upload image:
			<input name="product_image" type="file" /> <br />
			<input type="submit" value="Add product" />
		</form>
	</div>
</div>