<div id="main">
	<div id="filter-list">
		<div class="filter-title-div"><span class="filter-title">by category</span></div>
		<?php
		foreach ($this->categoryArray as $category):
			$style = '';
			$url = $this->selectedDevice;
			$action = $category;
			if ($category == $this->selectedCategory) {
	        	$style = ' style="border-bottom: 2px solid #444;"';
	        	$action = 'all';
	        }
		?>

        <div class="filter-link-div">
        	<a href="
			<?php
			echo $this->url(
            array('controller'=>'index', 'action'=> $action),
            'default',true) . '/' . $url; ?>" class="filter-link";

        	<?php echo $style . ">" . $category; ?>

        	</a>
        </div>
        <div class="filter-link-div">
        	<span class="filter-separator">|</span>
        </div>
		<?php endforeach; ?>
	</div>

	<div id="filter-list">
	<div class="filter-title-div"><span class="filter-title">by device</span></div>
	<?php
	foreach ($this->deviceArray as $device):
		$style = '';
		$url = $device;
		$action = 'all';
		if ($device == $this->selectedDevice) {
        	$style = 'style="border-bottom: 2px solid #444;"';
        	$url = '';
        }

		if($this->selectedCategory) {
			$action = $this->selectedCategory;
		}
	?>
	<div class="filter-link-div">
		<a href="
	<?php echo $this->url(
            array('controller'=>'index', 'action'=> $action),
            'default',true) . '/' . $url;?>" class="filter-link"

        <?php echo $style . ">" . $device; ?>
   		</a>
	</div>
	<div class="filter-link-div">
		<span class="filter-separator">|</span>
	</div>
	<?php endforeach;?>
	</div>

	<div id="product-list">
	<?php
	// class that retrieves and stores product id
	// for reuse as URL across multiple product items
	class Url {
		protected $id;

		public function __construct($id) {
			$this->id = $id;
		}

		public function createUrl() {
			return $this->id;
		}
	}
	
	if(is_array($this->productArray)) {
		foreach ($this->productArray as $product) {
		    echo '<div class="product-item">';

		    foreach ($product as $columnName=>$columnValue) {
		    	// if product-id is retrieved store it
		    	// else print product properties
			    if ($columnName == 'product-id') {
					$productUrl = new Url($columnValue);
		    		$productUrl = $productUrl->createUrl();
				}
				else {
		        echo '<div class="' . $columnName . '">';
				echo '<a href="' .
		        	$this->url(
		            array('controller'=>'product', 'action'=> $productUrl),
		            'default',true) . '">' . $columnValue . "</a></div>\n";
				}
		    }
		    echo "</div>\n";
		}
	}
	else {
		echo $this->productArray;
	}
	?>
	</div>
</div>