<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Mini eCommerce Site</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>

</head>
<body>
<div id="header">
    <div id="header-logo">
        <a href="<?php echo $this->url(
            array('controller'=>''),
            'default',
            true) ?>">Mini eCommerce Site</a>
    </div>
    <div id="header-navigation">
        <a href="<?php echo $this->url(
            array('controller'=>'product'),
            'default',
            true) ?>">Products</a>
        <a href="<?php echo $this->url(
            array('controller'=>'category'),
            'default',
            true) ?>">Categories</a>
        <a href="<?php echo $this->url(
            array('controller'=>'user'),
            'default',
            true) ?>">Users</a>
    </div>
</div>
 
<?php echo $this->layout()->content ?>
 
  <div id="notice"><br />
      <span>vagrant ssh</span><br />
      <span>mysqladmin -u root -psqlpass create mycms</span><br />
      <span>mysql -u root -psqlpass mycms &lt; /var/www/build/sql/schema.sql</span><br />
      <span>mysql -u root -psqlpass mycms &lt; /var/www/build/sql/load.sql</span><br />
      <span>sudo apt-get install php5-mcrypt</span>
  </div>
</body>
</html>