<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Mini eCommerce Site</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>

</head>
<body>
<div id="content">
  <div id="header">
      <div id="logo-div">
          <a href="<?php echo $this->url(
              array('controller'=>''),
              'default',
              true) ?>" id="logo-link">Mini eCommerce Site</a>
      </div>
      <div id="nav-div">
        <div class="nav-item">
          <a href="<?php echo $this->url(
              array('controller'=>'index'),
              'default',
              true) ?>" class="nav-link">Products</a>
          </div>
          <div class="nav-item">
          <a href="<?php echo $this->url(
              array('controller'=>'category'),
              'default',
              true) ?>" class="nav-link">Categories</a>
          </div>
          <div class="nav-item">
          <a href="<?php echo $this->url(
              array('controller'=>'user'),
              'default',
              true) ?>" class="nav-link">Accounts</a>
          </div>
      </div>
  </div>
 
  <?php echo $this->layout()->content ?>
 
  <div id="notice"><br />
      <span>vagrant ssh</span><br />
      <span>mysqladmin -u root -psqlpass create mycms</span><br />
      <span>mysql -u root -psqlpass mycms &lt; /var/www/build/sql/schema.sql</span><br />
      <span>mysql -u root -psqlpass mycms &lt; /var/www/build/sql/load.sql</span><br />
      <span>sudo apt-get install php5-mcrypt</span>
  </div>
</div>
</body>
</html>