<?php
// This file generated by Propel 1.7.0 convert-conf target
// from XML runtime conf file /var/www/Zend/build/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'induction' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=induction',
        'user' => 'root',
        'password' => 'sqlpass',
      ),
    ),
    'default' => 'induction',
  ),
  'log' => 
  array (
    'ident' => 'propel-induction',
    'level' => '7',
  ),
  'generator_version' => '1.7.0',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-propel-config.php');
return $conf;